import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const DEFAULT_EXCHANGE = "NSE";

/*
 FULL STREAMLIT MAPPING
 (Copied from your Streamlit version)
*/
const TICKER_CORRECTIONS: Record<string, string> = {
  "LIC HOUSING FINANCE LTD": "LICHSGFIN",
  "INOX WIND LIMITED": "INOXWIND",
  "HINDUSTAN ZINC LIMITED": "HINDZINC",
  "HINDUSTAN UNILEVER LTD.": "HINDUNILVR",
  "TATA TECHNOLOGIES LIMITED": "TATATECH",
  "SYNGENE INTERNATIONAL LTD": "SYNGENE",
  "MARUTI SUZUKI INDIA LTD.": "MARUTI",
  "KEI INDUSTRIES LTD.": "KEI",
  "JINDAL STEEL LIMITED": "JINDALSTEL",
  "CENTRAL DEPO SER (I) LTD": "CDSL",
  "BAJAJ FINANCE LIMITED": "BAJFINANCE",
  "MAHINDRA & MAHINDRA LTD": "M&M",
  "DABUR INDIA LTD": "DABUR",
  "TRENT LTD": "TRENT",
  "JIO FIN SERVICES LTD": "JIOFIN",
  "IIFL FINANCE LIMITED": "IIFL",
  "MUTHOOT FINANCE LIMITED": "MUTHOOTFIN",
  "BOSCH LIMITED": "BOSCHLTD",
  "HDFC LIFE INS CO LTD": "HDFCLIFE",
  "ASIAN PAINTS LIMITED": "ASIANPAINT",
  "DALMIA BHARAT LIMITED": "DALBHARAT",
  "BLUE STAR LIMITED": "BLUESTARCO",
  "HINDALCO INDUSTRIES LTD": "HINDALCO",
  "360 ONE WAM LIMITED": "360ONE",
  "PATANJALI FOODS LIMITED": "PATANJALI",
  "INDUSIND BANK LIMITED": "INDUSINDBK",
  "COAL INDIA LTD": "COALINDIA",
  "TATA MOTORS LIMITED": "TATAMOTORS",
  "INDIAN ENERGY EXC LTD": "IEX",
  "RELIANCE INDUSTRIES LTD": "RELIANCE",
  "GRASIM INDUSTRIES LTD": "GRASIM",
  "LIFE INSURA CORP OF INDIA": "LICI",
  "FEDERAL BANK LTD": "FEDERALBNK",
  "JSW STEEL LIMITED": "JSWSTEEL",
  "RAIL VIKAS NIGAM LIMITED": "RVNL",
  "PIDILITE INDUSTRIES LTD": "PIDILITIND",
  "MANAPPURAM FINANCE LTD": "MANAPPURAM",
  "BAJAJ AUTO LIMITED": "BAJAJ-AUTO",
  "DR. REDDY S LABORATORIES": "DRREDDY",
  "CIPLA LTD": "CIPLA",
  "CANARA BANK": "CANBK",
  "AVENUE SUPERMARTS LIMITED": "DMART",
  "STEEL AUTHORITY OF INDIA": "SAIL",
  "INDIAN RAIL TOUR CORP LTD": "IRCTC",
  "INFO EDGE (I) LTD": "NAUKRI",
  "INTERGLOBE AVIATION LTD": "INDIGO",
  "UNION BANK OF INDIA": "UNIONBANK",
  "BAJAJ FINSERV LTD.": "BAJAJFINSV",
  "SUN PHARMACEUTICAL IND L": "SUNPHARMA",
  "EXIDE INDUSTRIES LTD": "EXIDEIND",
  "BHARAT PETROLEUM CORP  LT": "BPCL",
  "TATA POWER CO LTD": "TATAPOWER",
  "HERO MOTOCORP LIMITED": "HEROMOTOCO",
  "MARICO LIMITED": "MARICO",
  "VODAFONE IDEA LIMITED": "IDEA",
  "BRITANNIA INDUSTRIES LTD": "BRITANNIA",
  "AU SMALL FINANCE BANK LTD": "AUBANK",
  "INDIAN RAILWAY FIN CORP L": "IRFC",
  "HINDUSTAN AERONAUTICS LTD": "HAL",
  "BHARAT FORGE LTD": "BHARATFORG",
  "BHARTI AIRTEL LIMITED": "BHARTIARTL",
  "AXIS BANK LIMITED": "AXISBANK",
  "PI INDUSTRIES LTD": "PIIND",
  "NBCC (INDIA) LIMITED": "NBCC",
  "BSE LIMITED": "BSE",
  "IDFC FIRST BANK LIMITED": "IDFCFIRSTB",
  "ITC LTD": "ITC",
  "AUROBINDO PHARMA LTD": "AUROPHARMA",
  "TVS MOTOR COMPANY  LTD": "TVSMOTOR",
  "EICHER MOTORS LTD": "EICHERMOT",
  "TATA ELXSI LIMITED": "TATAELXSI",
  "HAVELLS INDIA LIMITED": "HAVELLS",
  "TATA CONSULTANCY SERV LT": "TCS",
  "ICICI BANK LTD.": "ICICIBANK",
  "DLF LIMITED": "DLF",
  "NESTLE INDIA LIMITED": "NESTLEIND",
  "DIXON TECHNO (INDIA) LTD": "DIXON",
  "COMPUTER AGE MNGT SER LTD": "CAMS",
  "BIOCON LIMITED.": "BIOCON",
  "PAGE INDUSTRIES LTD": "PAGEIND",
  "ADANI PORT & SEZ LTD": "ADANIPORTS",
  "CYIENT LIMITED": "CYIENT",
  "ADANI GREEN ENERGY LTD": "ADANIGREEN",
  "COFORGE LIMITED": "COFORGE",
  "CUMMINS INDIA LTD": "CUMMINSIND",
  "SUZLON ENERGY LIMITED": "SUZLON",
  "HCL TECHNOLOGIES LTD": "HCLTECH",
  "AMBUJA CEMENTS LTD": "AMBUJACEM",
  "COLGATE PALMOLIVE LTD.": "COLPAL",
  "TATA CONSUMER PRODUCT LTD": "TATACONSUM",
  "KOTAK MAHINDRA BANK LTD": "KOTAKBANK",
  "NHPC LTD": "NHPC",
  "HDFC BANK LTD": "HDFCBANK",
  "LUPIN LIMITED": "LUPIN",
  "NMDC LTD.": "NMDC",
  "NTPC LTD": "NTPC",
  "CG POWER AND IND SOL LTD": "CGPOWER",
  "INDIAN OIL CORP LTD": "IOC",
  "KPIT TECHNOLOGIES LIMITED": "KPITTECH",
  "ABB INDIA LIMITED": "ABB",
  "LARSEN & TOUBRO LTD.": "LT",
  "ULTRATECH CEMENT LIMITED": "ULTRACEMCO",
  "INFOSYS LIMITED": "INFY",
  "GAIL (INDIA) LTD": "GAIL",
  "PETRONET LNG LIMITED": "PETRONET",
  "POWER FIN CORP LTD.": "PFC",
  "WIPRO LTD": "WIPRO",
  "REC LIMITED": "RECLTD",
  "ADANI ENERGY SOLUTION LTD": "ADANIENSOL",
  "ADANI ENTERPRISES LIMITED": "ADANIENT",
  "TATA STEEL LIMITED": "TATASTEEL",
  "RBL BANK LIMITED": "RBLBANK",
  "INDRAPRASTHA GAS LTD": "IGL",
  "YES BANK LIMITED": "YESBANK",
  "GLENMARK PHARMACEUTICALS": "GLENMARK",
  "TECH MAHINDRA LIMITED": "TECHM",
  "MPHASIS LIMITED": "MPHASIS",
  "SIEMENS LTD": "SIEMENS",
  "OIL INDIA LTD": "OIL",
  "JSW ENERGY LIMITED": "JSWENERGY",
  "LTIMINDTREE LIMITED": "LTIM",
  "ASHOK LEYLAND LTD": "ASHOKLEY",
  "DELHIVERY LIMITED": "DELHIVERY",
  "DIVI S LABORATORIES LTD": "DIVISLAB",
  "BANK OF BARODA": "BANKBARODA",
  "MULTI COMMODITY EXCHANGE": "MCX",
  "TITAN COMPANY LIMITED": "TITAN",
  "VOLTAS LTD": "VOLTAS",
  "SRF LTD": "SRF",
  "POLYCAB INDIA LIMITED": "POLYCAB",
  "BHARAT ELECTRONICS LTD": "BEL",
  "BANK OF INDIA": "BANKINDIA",
  "POWER GRID CORP. LTD.": "POWERGRID",
  "GODREJ PROPERTIES LTD": "GODREJPROP",
  "OIL AND NATURAL GAS CORP.": "ONGC",
  "STATE BANK OF INDIA": "SBIN",
  "SHREE CEMENT LIMITED": "SHREECEM",
  "PUNJAB NATIONAL BANK": "PNB",
  "UNITED SPIRITS LIMITED": "UNITDSPR",
  "UPL LIMITED": "UPL",
  "VARUN BEVERAGES LIMITED": "VBL",
  "VEDANTA LIMITED": "VEDL",
  "MAX HEALTHCARE INS LTD": "MAXHEALTH",
  "MAZAGON DOCK SHIPBUIL LTD": "MAZDOCK",
  "TATA CHEMICALS LTD": "TATACHEM",
  "WAAREE ENERGIES LIMITED": "WAAREEENER"
};

export async function GET(request: NextRequest) {
  try {
    const baseUrl = process.env.AWS_API_URL;
    const secret = process.env.RADAR_SECRET;

    if (!baseUrl || !secret) {
      return NextResponse.json(
        { error: "Missing environment variables" },
        { status: 500 }
      );
    }

    const awsUrl = new URL(baseUrl);
    awsUrl.searchParams.set("route", "smart-radar");
    awsUrl.searchParams.set("secret", secret);

    const date = request.nextUrl.searchParams.get("date");
    if (date) {
      awsUrl.searchParams.set("date", date);
    }

    const res = await fetch(awsUrl.toString(), { cache: "no-store" });

    const data = await res.json();

    if (!res.ok) {
      return NextResponse.json(data, { status: res.status });
    }

    const rows = Array.isArray(data) ? data : [];

    // Attach TradingView mapping
    const enriched = rows.map((stock: any) => {
      const cleaned =
        TICKER_CORRECTIONS[stock.Name] ||
        stock.Name.replace(/&/g, "").replace(/\s+/g, "");

      const tvSymbol = `${DEFAULT_EXCHANGE}:${cleaned}`;

      return {
        ...stock,
        TV_Symbol: tvSymbol,
        Chart: `https://www.tradingview.com/chart/?symbol=${tvSymbol}`
      };
    });

    return NextResponse.json(enriched);

  } catch (error: any) {
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}
