import Link from "next/link";
import { DatePicker, AutoRefresh } from "@/components/Controls";
import { getTodayIstDate } from "@/utils/backend";
import { getInternalApiUrl, fetchInternalApi } from "@/utils/internalApi";
export const dynamic="force-dynamic";
type Signal={time:string;side:string;strategy:string;level:number;entry:number;stop:number;target:number;outcome:string;generated_at?:string;exit_time?:string;market_oi?:Record<string,{pct:number}>;wall_oi?:Record<string,{pct:number}>};
export default async function Page({searchParams}:{searchParams:Promise<{date?:string}>}) {
  const date=(await searchParams).date??getTodayIstDate();
  const response=await fetchInternalApi(await getInternalApiUrl(`/api/nifty-signals?date=${encodeURIComponent(date)}`));
  const data=await response.json(); const signals:Signal[]=data.signals??[];
  const replay=data.mode==="RESEARCH_REPLAY";
  const stale=Boolean(data.stale);
  return <main className="p-6 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">Nifty OI Signals</h1><p className="text-sm text-slate-400">Prior-session OI walls · reversal &amp; break/retest · 10:30–14:00 IST · 1:3 index risk/reward</p></div><div className="flex gap-3"><DatePicker/><AutoRefresh/></div></div>
    <section className="rounded-xl border border-slate-700 bg-slate-900 p-5 space-y-2"><p className="font-semibold text-cyan-300">{replay?"Historical research replay":"Live paper scanner — no orders"}</p><p>{data.error??data.status}</p>{data.checked_at&&<p className="text-sm text-slate-400">Last checked: {new Date(data.checked_at).toLocaleString("en-GB",{timeZone:"Asia/Kolkata"})} IST</p>}{data.reason&&<p className="text-amber-300">{data.reason}</p>}{data.levels_date&&<p className="text-sm">OI levels from {data.levels_date} · expiry {data.expiry} · support {data.support?.join(", ")} · resistance {data.resistance?.join(", ")}</p>}<p className="text-sm text-slate-400">Signals require positive put OI and negative call OI changes for bulls; the reverse for bears, across both ATM ±200 and wall ±50 baskets. Uses completed 10-minute OI changes with one-minute lag.</p>{!replay&&<p className="text-sm text-slate-400">One open paper trade and at most two entries per day. Entry is the fresh quote when generated; delayed or incomplete data suppresses entries.</p>}</section>
    {stale&&<p className="text-amber-300">The last report is over seven minutes old. The scanner runs 09:00–16:55 IST; current scanner activity cannot be confirmed from this report.</p>}
    {!signals.length?<p className="p-5 text-slate-400">{data.error?"Results unavailable.":"No qualifying signals for the selected date."}</p>:<div className="grid gap-4">{signals.map((s,i)=><article key={i} className="rounded-xl border border-slate-700 p-5 space-y-3"><div className="flex justify-between"><h2 className={s.side==="BULL"?"text-emerald-400 font-bold":"text-rose-400 font-bold"}>{s.time} IST · {s.side} · {s.strategy.replaceAll("_"," ")}</h2><span>{s.outcome}{s.exit_time?` at ${s.exit_time}`:""}</span></div><div className="flex flex-wrap gap-6"><span>OI line {s.level.toFixed(0)}</span><span>Entry {s.entry.toFixed(2)}</span><span>Stop {s.stop.toFixed(2)}</span><span>Target {s.target.toFixed(2)}</span></div>{s.generated_at&&<p className="text-sm text-slate-400">Generated: {new Date(s.generated_at).toLocaleTimeString("en-GB",{timeZone:"Asia/Kolkata"})} IST</p>}{s.market_oi&&<p className="text-sm">10-minute OI: ATM PE {s.market_oi.PE.pct.toFixed(2)}%, CE {s.market_oi.CE.pct.toFixed(2)}% · wall PE {s.wall_oi?.PE.pct.toFixed(2)}%, CE {s.wall_oi?.CE.pct.toFixed(2)}%</p>}<Link className="text-cyan-300 text-sm" href={`/charts?symbol=NIFTY%2050&date=${date}`}>View session chart →</Link></article>)}</div>}
    <p className="text-xs text-slate-500">Research replay uses index points and simulated fills. The seven historical trades are an in-sample benchmark, not a live accuracy estimate. Live paper outcomes use completed subsequent candles; a candle hitting both stop and target is scored as stop.</p>
  </main>;
}
