'use client';
import {useEffect,useRef,useState,useReducer} from 'react';
import {Cat,Plus,Check,ExternalLink,X} from 'lucide-react';
import {addChartWatchlistSymbol,readChartWatchlist,CHART_WATCHLIST_UPDATED_EVENT} from '@/utils/chartWatchlist';
import {buildTradingViewUrl,getTodayIstDate} from '@/utils/backend';
import {PALLAS_DATES,quoteKey,pallasAiScore,passesPallasAi,pallasEngineLabel,pallasAiPassLabel,type PallasSignal,type PallasCandidate,type PallasBar} from '@/utils/pallas';
import {pallasSessionRollover,pallasPreviousWeekday} from '@/utils/pallasTime';
import {initialPallasRefresh,pallasRefreshReducer,pallasRefreshView} from '@/utils/pallasRefresh';
import './pallas.css';
const fmt=(v:unknown,d=2)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-IN',{maximumFractionDigits:d}):'—';
const hm=(v?:string|null)=>v?new Date(v).toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata',hour12:false}):'—';
const clock=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function PriceChart({bars,event}:{bars:PallasBar[];event:PallasSignal}){
  if(!bars.length)return <div className="empty">Completed candles unavailable at this time.</div>;
  const levels=[{p:event.Breakout_Level??event.Pole_Extreme,label:'Breakout',color:'#5ad9ee'},...(event.Prior_OI_Line?[{p:event.Prior_OI_Line,label:'Prior OI',color:'#b8a0f5'}]:[])];
  const high=Math.max(...bars.map(b=>b[3]),...levels.map(l=>l.p)),low=Math.min(...bars.map(b=>b[4]),...levels.map(l=>l.p)),span=Math.max(high-low,.01),y=(p:number)=>25+(high-p)/span*220,dx=520/bars.length;
  return <svg viewBox="0 0 650 285" role="img" aria-label={`${event.Symbol} completed five-minute candles and prior OI level`}>
    {[0,1,2,3,4].map(i=><g key={i}><line x1="10" x2="535" y1={25+i*55} y2={25+i*55} stroke="#243047"/><text x="545" y={29+i*55} fill="#8e9eb7" fontSize="10">{fmt(high-i/4*span)}</text></g>)}
    {levels.map(l=><g key={l.label}><line x1="10" x2="535" y1={y(l.p)} y2={y(l.p)} stroke={l.color} strokeDasharray="5 4"/><text x="545" y={y(l.p)-5} fill={l.color} fontSize="10">{l.label} {fmt(l.p)}</text></g>)}
    {bars.map((b,i)=><g key={b[1]}><line x1={10+(i+.5)*dx} x2={10+(i+.5)*dx} y1={y(b[3])} y2={y(b[4])} stroke={b[5]>=b[2]?'#49d5a2':'#ff7589'}/><rect x={10+(i+.18)*dx} y={Math.min(y(b[2]),y(b[5]))} width={Math.max(2,dx*.64)} height={Math.max(1,Math.abs(y(b[2])-y(b[5])))} fill={b[5]>=b[2]?'#49d5a2':'#ff7589'}/>{i%6===0&&<text x={10+i*dx} y="275" fontSize="10" fill="#8e9eb7">{b[1]}</text>}</g>)}
  </svg>;
}
export default function PallasClient(){
  const [mode,setMode]=useState('live'),[date,setDate]=useState(getTodayIstDate),[minute,setMinute]=useState(690),[play,setPlay]=useState(false),[search,setSearch]=useState(''),[side,setSide]=useState('ALL'),[onlyOi,setOnlyOi]=useState(false),[onlyAi,setOnlyAi]=useState(false),[onlyWatch,setOnlyWatch]=useState(false),[watch,setWatch]=useState<string[]>([]),[selected,setSelected]=useState<PallasSignal|null>(null),[chart,setChart]=useState<PallasBar[]>([]),[notice,setNotice]=useState('');
  const [refresh,dispatchRefresh]=useReducer(pallasRefreshReducer,initialPallasRefresh);
  const sessionKey=`${mode}|${date}|${mode==='research'?minute:''}`;
  const {data,error}=pallasRefreshView(refresh,sessionKey);
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{
    if(mode!=='live')return;
    const sync=()=>{const next=pallasSessionRollover(mode,date);if(next){setSelected(null);setDate(next);}};
    sync();const timer=setInterval(sync,5000);document.addEventListener('visibilitychange',sync);
    return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',sync);};
  },[mode,date]);
  useEffect(()=>{const sync=()=>setWatch(readChartWatchlist());sync();window.addEventListener(CHART_WATCHLIST_UPDATED_EVENT,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(CHART_WATCHLIST_UPDATED_EVENT,sync);window.removeEventListener('storage',sync);};},[]);
  useEffect(()=>{let disposed=false,controller:AbortController|undefined,timer:ReturnType<typeof setTimeout>;const load=async()=>{controller=new AbortController();try{const p=new URLSearchParams({mode,date});if(mode==='research')p.set('asof',clock(minute));const r=await fetch('/api/pallas?'+p,{cache:'no-store',signal:controller.signal});if(r.status===401){window.location.assign('/login?next=%2Fpallas');return;}const body=await r.json();if(!r.ok)throw new Error(body.error??'Feed unavailable');if(!disposed)dispatchRefresh({type:'success',key:sessionKey,data:body});}catch(e){if(!disposed&&!(e instanceof DOMException&&e.name==='AbortError'))dispatchRefresh({type:'failure',key:sessionKey,error:e instanceof Error?e.message:'Feed unavailable'});}finally{if(!disposed&&mode==='live')timer=setTimeout(load,5000);}};dispatchRefresh({type:'reset',key:sessionKey});load();return()=>{disposed=true;controller?.abort();clearTimeout(timer);};},[mode,date,minute,sessionKey]);
  useEffect(()=>{if(!play||mode!=='research')return;const t=setInterval(()=>setMinute(m=>{if(m>=690){setPlay(false);return m;}return m+5;}),1000);return()=>clearInterval(t);},[play,mode]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),2500);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>{if(!selected)return;if(mode==='research'&&Date.parse(selected.Issued_At)>Date.parse(`${date}T${clock(minute)}:00+05:30`)){setSelected(null);return;}const c=new AbortController();const p=new URLSearchParams({mode,date,symbol:selected.Symbol});if(mode==='research')p.set('asof',clock(minute));setChart([]);fetch('/api/pallas?'+p,{cache:'no-store',signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>setChart(d.bars??[])).catch(()=>{});return()=>c.abort();},[selected,mode,date,minute,data?.cut]);
  useEffect(()=>{if(selected&&!dialog.current?.open)dialog.current?.showModal();else if(!selected)dialog.current?.close();},[selected]);
  const quotes=new Map((data?.quotes??[]).map(q=>[`${q.symbol}|${q.expiry}|${q.strike}|${q.leg}`,q]));
  const change=(s:PallasSignal)=>{const q=quotes.get(quoteKey(s));return q&&s.Reference_Premium>0?(q.ltp/s.Reference_Premium-1)*100:null;};
  const show=(symbol:string,direction:string,oi:boolean)=>symbol.includes(search.toUpperCase())&&(side==='ALL'||direction===side)&&(!onlyOi||oi)&&(!onlyWatch||watch.includes(symbol));
  const all=new Map<string,PallasSignal>();for(const s of data?.signals??[]){const old=all.get(s.Symbol);if(!old||s.Event_Type==='CONFIRMED_CLOSE')all.set(s.Symbol,s);}
  // Recorded history retains every event, including multiple alerts for one stock.
  const recorded=mode==='history'?(data?.signals??[]):[...all.values()];
  const signals=recorded.filter(s=>show(s.Symbol,s.Side,Boolean(s.Line_Respect))&&(!onlyAi||passesPallasAi(s))).sort((a,b)=>(change(b)??-Infinity)-(change(a)??-Infinity)||a.Symbol.localeCompare(b.Symbol));
  const now=mode==='live'?Date.now():data?Date.parse(data.asof):0,newSignals=signals.filter(s=>now-Date.parse(s.Issued_At)<300000),active=signals.filter(s=>!newSignals.includes(s));
  const candidates=(data?.candidates??[]).filter(c=>!all.has(c.symbol)&&show(c.symbol,c.side,false)).sort((a,b)=>b.pole_move_pct-a.pole_move_pct);
  const tools=(symbol:string)=><div className="card-actions"><button title="Add to Charts watchlist" aria-label={`Add ${symbol} to Charts watchlist`} disabled={watch.includes(symbol)} onClick={()=>{setWatch(addChartWatchlistSymbol(symbol));setNotice(symbol+' added to Charts watchlist');}}>{watch.includes(symbol)?<Check size={12}/>:<Plus size={12}/>}</button><a href={buildTradingViewUrl(symbol)} target="_blank" rel="noopener noreferrer" aria-label={`Open ${symbol} on TradingView`} title="Open TradingView"><ExternalLink size={12}/></a></div>;
  const card=(s:PallasSignal)=>{const q=quotes.get(quoteKey(s)),chg=change(s);const staleQuote=q&&(Boolean(error)||(mode!=='history'&&now-Date.parse(q.received_at)>420000));const ai=pallasAiScore(s),engine=pallasEngineLabel(s);return <article key={s.Event_ID} className={'card '+(newSignals.includes(s)?'new':'')}><div className="card-head"><button className="inspect" onClick={()=>setSelected(s)}><strong>{s.Symbol}</strong><span className={'side '+s.Side.toLowerCase()}>{s.Side}</span><span className={'ai-pill '+(ai!==null&&ai>=.70?'high':'')} title={ai===null?'AI score unavailable until candle confirmation':'Experimental model score, not a calibrated success probability'}>AI {ai===null?'—':fmt(ai*100,1)}</span></button>{tools(s.Symbol)}</div><div className="contract">{s.Selected_Strike} · {s.Expiry.slice(5)}<span>{s.Signal_Time||hm(s.Issued_At).slice(0,5)}</span></div><div className="engine-row"><span className="engine-label" title={engine.detail}>{engine.label}</span><span className={passesPallasAi(s)?'engine-pass passed':'engine-pass'}>{pallasAiPassLabel(s)}</span></div><div className="prices"><div><small>Reference</small><b>₹{fmt(s.Reference_Premium)}</b></div><div><small>{staleQuote?'Stale quote':mode==='history'?'Last session quote':'Latest quote'}</small><b>₹{fmt(q?.ltp)}</b></div><strong className={chg!==null&&chg>=0?'green':'red'}>{chg===null?'—':`${chg>=0?'+':''}${fmt(chg)}%`}</strong></div><div className="oi">{s.Prior_OI_Line?`${s.Prior_OI_Line_Type} ${fmt(s.Prior_OI_Line)}${s.Line_Respect?' · respected':''}`:'Matching prior OI wall unavailable'}</div><div className="wall-build"><span>Intraday Wall Buildup</span><strong>{s.Intraday_Wall_Buildup_Pct==null?'—':`${s.Intraday_Wall_Buildup_Pct>=0?'+':''}${fmt(s.Intraday_Wall_Buildup_Pct,1)}%`} <small>({fmt(s.Intraday_Wall_OI_Added,0)} OI)</small></strong></div><div className="event-status"><span>{s.Event_Type==='EARLY_TICK'?'Early tick · '+s.Confirmation_Status.replaceAll('_',' ').toLowerCase():'Candle confirmed'}{s.Recovered?' · recovered':''}</span><span>OI {hm(s.Chain_Received_At).slice(0,5)}</span></div></article>;};
  const candidateCard=(c:PallasCandidate)=><article className="card" key={c.symbol}><div className="card-head"><strong>{c.symbol}</strong>{tools(c.symbol)}</div><div className="contract"><span className={'side '+c.side.toLowerCase()}>{c.side}</span> · ₹{fmt(c.spot)}</div><div className="small-grid"><span>Pole <b>{fmt(c.pole_move_pct)}%</b></span><span>Pullback <b>{fmt(c.flag_pb_pct)}%</b></span></div><div className="oi">Breakout level {fmt(c.pole_extreme)}</div></article>;
  return <div className="pallas-view"><header className="header"><div className="identity"><div className="cat"><Cat size={27}/></div><div><h1>Pallas <span className="tag">FRONTIER 1</span></h1><p>Pole → Flag → Breakout</p></div></div><div className="controls"><select aria-label="Mode" value={mode} onChange={e=>{const m=e.target.value;setMode(m);setDate(m==='live'?getTodayIstDate():m==='history'?pallasPreviousWeekday():PALLAS_DATES.at(-1)!);setPlay(false);setSelected(null);}}><option value="live">Live</option><option value="history">Historical signals</option><option value="research">Research replay</option></select>{mode==='research'?<select aria-label="Session" value={date} onChange={e=>{setDate(e.target.value);setSelected(null);}}>{PALLAS_DATES.map(d=><option key={d}>{d}</option>)}</select>:mode==='history'?<input type="date" aria-label="Historical session" max={getTodayIstDate()} value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setSelected(null);}}}/>:<span className="mono">{date}</span>}</div></header>
  <div className="content"><div className="summary"><div>Signals <b>{recorded.length}</b></div><div>Bull / Bear <b><span className="green">{recorded.filter(s=>s.Side==='BULL').length}</span> / <span className="red">{recorded.filter(s=>s.Side==='BEAR').length}</span></b></div><div>OI respected <b className="purple">{recorded.filter(s=>s.Line_Respect).length}</b></div><div>Snapshot <b>{data?.cut??'—'}</b></div></div>
  {mode==='research'&&<section className="replay"><b className="mono">{clock(minute)} IST</b><button onClick={()=>setPlay(!play)}>{play?'Pause':'▶ Play'}</button><button onClick={()=>{setPlay(false);setMinute(555);}}>↺</button><div><input aria-label="Historical replay time" type="range" min="555" max="690" step="5" value={minute} onChange={e=>{setPlay(false);setMinute(Number(e.target.value));}}/><div className="ticks"><span>09:15</span><span>10:00</span><span>10:45</span><span>11:30</span></div></div></section>}
  <div className={'status '+(error||data?.stale?'warning':'')} role="status">{error?`Refresh failed: ${error}`:data?.status||'Loading session…'}{error&&data?` · Showing last available data ${hm(data.checked_at??data.asof)} IST; data may be stale`:''}{data?.stale&&!error?' · capture is stale':''}{mode==='live'&&data?.tick_connected===false?' · tick stream disconnected':''}</div>
  <div className="board-top"><h2>The signal desk</h2><div className="filters"><input type="search" aria-label="Search symbol" placeholder="Search symbol…" value={search} onChange={e=>setSearch(e.target.value)}/>{['ALL','BULL','BEAR'].map(s=><button key={s} className={side===s?'on':''} onClick={()=>setSide(s)}>{s==='ALL'?'All':s==='BULL'?'Bull':'Bear'}</button>)}<button aria-pressed={onlyAi} className={onlyAi?'on':''} title="Filter confirmed signals by frozen AI score; forming setups stay visible" onClick={()=>setOnlyAi(!onlyAi)}>AI ≥70</button><button aria-pressed={onlyWatch} className={onlyWatch?'on':''} onClick={()=>setOnlyWatch(!onlyWatch)}>Watchlist</button><button aria-pressed={onlyOi} className={onlyOi?'on':''} onClick={()=>setOnlyOi(!onlyOi)}>◇ OI respected</button></div></div>
  <div className="board">{[{name:'New breakouts',color:'cyan',items:newSignals.map(card)},{name:'Active signals',color:'green',items:active.map(card)},{name:'Flag forming',color:'amber',items:candidates.filter(c=>c.stage==='flag').map(candidateCard)},{name:'Pole watch',color:'purple',items:candidates.filter(c=>c.stage==='pole').map(candidateCard)}].map(l=><section className="lane" key={l.name}><div className="lane-head"><h3 className={l.color}>{l.name}</h3><span className="lane-count">{l.items.length}</span></div><div className="stack">{l.items.length?l.items:<div className="empty">No matching setups at this time.</div>}</div></section>)}</div>
  <footer>Active signals sorted by option change ↓ · AI scores at confirmation · Quoted premium, not booked profit<span>{mode==='research'?'Causal closed candles · receipt latency unknown':mode==='history'?'Recorded session · original alert times and scores':'Early ticks use the last available OI capture'}</span></footer></div>
  <dialog ref={dialog} className="pallas-inspector" onClose={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}}>{selected&&<div className="inspector"><div className="inspector-head"><div><h2>{selected.Symbol} <span className={'side '+selected.Side.toLowerCase()}>{selected.Side}</span></h2><p>{selected.Selected_Strike} · {selected.Expiry} · {hm(selected.Issued_At)} IST</p></div><button onClick={()=>setSelected(null)} aria-label="Close inspector"><X size={18}/></button></div><div className="detail-metrics"><div>Breakout spot<b>{fmt(selected.Breakout_Spot)}</b></div><div>Reference premium<b>₹{fmt(selected.Reference_Premium)}</b></div><div>Latest quote<b>₹{fmt(quotes.get(quoteKey(selected))?.ltp)}</b></div></div><div className="chart-panel"><span>Stock price · completed 5m candles</span><PriceChart bars={chart} event={selected}/></div><div className="facts">{[['Engine',pallasEngineLabel(selected).label],['AI threshold',pallasAiPassLabel(selected)],['Signal time',selected.Signal_Time+' IST'],['Issued at',hm(selected.Issued_At)+' IST'],['AI score',pallasAiScore(selected)===null?'—':`${fmt(pallasAiScore(selected)!*100,1)} / 100 · experimental`],['Pole move',`${fmt(selected.Pole_Move_Pct)}%`],['Pole body',`${fmt(selected.Pole_Body_Pct)}%`],['Flag pullback',`${fmt(selected.Flag_Pullback_Pct)}%`],['Pole / flag',`${fmt(selected.PF_Ratio)}×`],['Strike concentration',`${fmt(selected.Volume_Share_Pct)}%`],['Flow',selected.Flow_Type],['Prior OI line',fmt(selected.Prior_OI_Line)],['Intraday Wall Buildup',`${fmt(selected.Intraday_Wall_Buildup_Pct)}% (${fmt(selected.Intraday_Wall_OI_Added,0)} OI)`],['OI capture',`${hm(selected.Chain_Received_At)} IST`],['OI age at signal',`${fmt(selected.OI_Age_Seconds,0)} sec`],['Alert',selected.Event_Type==='EARLY_TICK'?'Early tick':'Candle confirmed'],['Confirmation',selected.Confirmation_Status.replaceAll('_',' ')]].map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}</div><p className="muted">Premium is a timestamped reference quote. Early tick alerts can fail candle-close confirmation.</p><a href={'/charts?symbol='+encodeURIComponent(selected.Symbol)+'&date='+date}>Open in Charts →</a></div>}</dialog><div className="watch-status" role="status">{notice}</div></div>;
}
